version: 2
updates:
  - package-ecosystem: "npm"
    directory: './template/console'
    schedule:
      interval: "weekly"
      # Check for npm updates on Sundays
      day: "sunday"
      time: '08:00'
      # Use ShangHai Standard Time (UTC +08:00)
      timezone: 'Asia/Shanghai'
  - package-ecosystem: "npm"
    directory: './template/mobile'
    schedule:
      interval: "weekly"
      # Check for npm updates on Sundays
      day: "sunday"
      time: '10:00'
      # Use ShangHai Standard Time (UTC +08:00)
      timezone: 'Asia/Shanghai'
    open-pull-requests-limit: 10
  - package-ecosystem: "npm"
    directory: './template/default'
    schedule:
      interval: "weekly"
      # Check for npm updates on Sundays
      day: "sunday"
      time: '11:00'
      # Use ShangHai Standard Time (UTC +08:00)
      timezone: 'Asia/Shanghai'
    open-pull-requests-limit: 10
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: "daily"
      time: '08:00'
      # Use ShangHai Standard Time (UTC +08:00)
      timezone: 'Asia/Shanghai'
    open-pull-requests-limit: 10